{% set name = "numpydoc" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/numpydoc-{{ version }}.tar.gz
  sha256: b0db7b75a32367a0e25c23b397842c65e344a1206524d16c8069f0a1c91b5f4c

build:
  skip: True  # [py<37]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - jinja2 >=2.10
    - sphinx >=3.0

test:
  imports:
    - numpydoc
  requires:
    - pip
  commands:
    - pip check || true  # [not win]
    - pi check || exit 0  # [win]

about:
  home: https://github.com/numpy/numpydoc
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Numpy's Sphinx extensions
  dev_url: https://github.com/numpy/numpydoc
  doc_url: https://numpydoc.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - jschueller
    - scopatz
