{% set name = "numpydoc" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/numpydoc-{{ version }}.tar.gz
  sha256: 866e5ae5b6509dcf873fc6381120f5c31acf13b135636c1a81d68c166a95f921

build:
  # sphinx >=7.2.0 requires py>=39, we didn't build sphinx >5.0.2,<7.3.7.
  skip: True  # [py<39]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - sphinx >=6
    - tabulate >=0.8.10
    - tomli >=1.1.0  # [py311]

test:
  imports:
    - numpydoc
  requires:
    - pip
    - pytest
    - matplotlib-base
  commands:
    - pip check
    - pytest --pyargs numpydoc

about:
  home: https://github.com/numpy/numpydoc
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Sphinx extension to support docstrings in Numpy format
  description: |
    Numpy's documentation uses several custom extensions to Sphinx. These are shipped in this numpydoc package, in case you want to make use of them in third-party projects.
    The numpydoc extension provides support for the Numpy docstring format in Sphinx, and adds the code description directives np:function, np-c:function, etc. that support the Numpy docstring syntax.
  dev_url: https://github.com/numpy/numpydoc
  doc_url: https://numpydoc.readthedocs.io/

extra:
  recipe-maintainers:
    - jschueller
    - scopatz
