{% set version = "0.9.0" %}

package:
  name: numpydoc
  version: {{ version }}

source:
  fn: numpydoc-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/n/numpydoc/numpydoc-{{ version }}.tar.gz
  sha256: 45e897ffc7f3e6962f6a02ea996d1661d99011f3d68fee450dc33056b60da84e

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - sphinx

test:
  imports:
    - numpydoc

about:
  home: https://github.com/numpy/numpydoc
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: Sphinx extension to support docstrings in Numpy format
  description: |
    Numpy's documentation uses several custom extensions to Sphinx. These are
    shipped in this numpydoc package, in case you want to make use of them
    in third-party projects.
  doc_url: https://pypi.python.org/pypi/numpydoc
  doc_source_url: https://github.com/numpy/numpydoc/blob/master/README.rst
  dev_url: https://github.com/numpy/numpydoc

extra:
  recipe-maintainers:
    - jschueller
    - scopatz
