travis:
  secure:
    BINSTAR_TOKEN: qD4qz1/qJ9As9UneDsPowaKQXacNVx5+HP8VdF7FW/Lp0pgDueJWwY2la07AJ5itzFeBtdRLn08BIW7hNFOmnLUKZVGhT6gD2JQvqkTSdt7hCtEmXGofsIzX4KE4oYgjEOswhXPK+SWRGeavD5n3aXXP/sRkkFpk0LglCgnOZjIvyAAqvJ52Tc2j82qOR0wUO8T6urbzILbCOMTOUWhQqqoE97c2YeAIU3e//MMVbDUTDghnsvraHR+g4Ax6gVxXqYs0p9FxNeuxFp3EbkwlAD9NuytDzr8pEhTSfiuJVBe2yr42W3ZbIT3Xn4B9GS6Qphq+kZ7p74ukkp0qfbc4jx/mtBrxinBXokWHi1ipi8uktjSHUPoVeXtR+hWK2kbOppK4r/6uYaGEnVDFa92dsfiMGLy3OF7g10ShBQ8/u8Cheoef7JcC7gZCw4FUhcmxL05uOrzof5H5oUQUxqhiVtmrEPUZXCYBWtznfn7A62/YzE48ht+TZBgvku1kQmzYtVNxhUIZoZ+usdXU5/nHerofvLQGpJYaMouZ1ofEwP/G77ahOuXTFW9dEABCYoPPD59kHNbXywwekk/SfC+XICVIPsY+DbMQVHD4MRd/wqOhh8z01U/EStWXrHoaKYL+vECya4MXWX7TrFo4SxGDIWWpi5tHaIedTk0OOBrHks8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
