travis:
  secure:
    BINSTAR_TOKEN: Q+jGmj9TnczSxD3qTyeM3zNEPZbKFI7tfTMbNvXknwiQTXcDl2cdBbe+aB0He0sGlyrHu07tAj89YNYE9OcpbJ7VJi/mCGiHJ/TeX/H8Fas/veeW1yNYk3ZJX16U12V85h82W1n8EbwsNWikGEMyR5jWqMM/RH0SSkTwA1rYaazEwb3l/BCa/cxwQ+PeNcsCABN0ig8ZHG/nmjNYdBQeAYJR7qDHzdKdLJHluQKCGCL6IEbFft4BLiVY9b0/Ek5/FKvjCRSGKCljQ3O79NXtI4aQOkTVgBWw8JXk0Zv+VdA187PD5+A+Iqv/MQ3HH8ArtEHA2dpA/aIAo7DJD/4CSY1Pc9WqnAytY7OZZ20LV8Y9Z8BgxSa4qAo08x3wxymsbKI5h92yIyhaG1E8zzySBphaCSYTeHvjE8clpk40lLDn2YEE+SOw3P8zQq7qM2zgiPcBB/Nj3PK2rI1Qd0XScHlCvlmlFbUU/zwn38mjo1ZX6Xou0jkmqnxIw7qAtWHnPT0CLWQeIYBHUg70UKDzqo0DpwAB2+ceaCSYF4+B3KXvayVHNscR3tAkUV9PjgmKplWkMfQl9CWbItGHfcr1l2kRsGV8F/m54QLmP3lUkGG5gRN8IBgKGgkb9y8pxtI47jKMZ3K7EtGNF/YUSkfWvBlwXwOUJnqWxdVhhYf3tI8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
