travis:
  secure:
    BINSTAR_TOKEN: eohPkh4/yAencQ+EikydHRr3p7QKWgqlaWlDQrwiUvUX1EwiUwlWHwLO1CGTsDMapqvZXmdUERmrpBUk1gBJPYqstngE5kG/w/BGa9oDs9Gv/rFV96LU9n4si8iblTUCUOdoMA4+3L2UBzinInzrkOyn0/f/PigW0iu+pZcIJ84pfYIzrXvx/nzjSbLOEEGBSIhzT/AlAqMotW5Cp8QQK1ZyJqLnFcEMmcqrHEHfWWeWMueFGmILSp8NqegeoEbUlBFODUftdpcSfn7c7Af+jh0hYn08G+VOU1wmVQ9TpWvwryFe6gYES8p9o5HbKIr//IziVWyj/2fXfkxwBAkaZpEJYeog8tKqSVNoKvH8Yfla8+uQAom71qXQq9vzs+Gn8MUGnV/tmaMrLgVo0xva6SmP88Q1MA/NKDdHjtoYbTEsi9fJQZSD+AfKDSIWHPWxuRil2yHR0NlTEto5sXSp7S33xtJsmJMbqFBMtMhWQ5lcrkwV44OOMV0PHhplqxcAzlA+E9pe5V4moG8hHZeX5MYJvlHPGktHRnesUVlW2Y7cV4KCmtSyd+xCI0YMNZv13tvxIWBP01Vhns7g+zLQ+X4hQMAI92QOR6QTJsdSmfSmZSgfric/t1Sck+ZEH+MgzrzN9bbt247lOwm9RWepsuS6pZ4dTOhuBl9GcOOHSd0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
